# Generated by Django 4.2.6 on 2023-11-02 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_ourproduct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ourproduct',
            new_name='Game',
        ),
    ]
