# Generated by Django 4.2.6 on 2023-11-02 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_ourproduct_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='sort',
        ),
    ]
